plugins {
    id 'maven-publish'
    id 'fabric-loom' version '1.18.2' apply false
    id 'net.fabricmc.fabric-loom-remap' version '1.18.2' apply false
    id 'com.replaymod.preprocess' version 'a2223f4'
}

preprocess {
    strictExtraMappings = false

    def mc260102 = createNode('26.1.2', 26_01_02, '')
    def mc260200 = createNode('26.2', 26_02_00, '')

    mc260102.link(mc260200, file('versions/mapping-26.1.2-26.2.txt'))

    for (final def node in getNodes()) {
        findProject(node.project).ext.mcVersion = node.mcVersion
    }
}

tasks.register('buildAndGather') {
    group = 'build'
    description = 'Build every Minecraft version and gather all mod jars into the mods/ directory.'

    subprojects {
        dependsOn project.tasks.named('build').get()
    }

    doFirst {
        println 'Gathering builds into mods/'
        def modsDir = rootProject.file('mods')
        delete modsDir
        modsDir.mkdirs()
        subprojects {
            copy {
                from(project.layout.buildDirectory.dir('libs')) {
                    include '*.jar'
                    exclude '*-dev.jar', '*-sources.jar', '*-shadow.jar'
                }
                into modsDir
                duplicatesStrategy = DuplicatesStrategy.INCLUDE
            }
        }
    }
}