name: Dev Builds

on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "settings.json"
      - "src/**"
      - "versions/**"
      - ".github/workflows/**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit